package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 03 11:06:49 IST 2024
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void insertDeptToDatabase(int deptId, String deptName);
}

