package model;

import model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 03 11:03:05 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl) findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for ProggrammaticDepartmentsView1.
     * @return ProggrammaticDepartmentsView1
     */
    public ProggrammaticDepartmentsViewImpl getProggrammaticDepartmentsView1() {
        return (ProggrammaticDepartmentsViewImpl) findViewObject("ProggrammaticDepartmentsView1");
    }
    
    public void insertDeptToDatabase(int deptId, String deptName){
        ViewObjectImpl departmentsView1 = this.getDepartmentsView1();
        Row createRow = departmentsView1.createRow();
        createRow.setAttribute("DepartmentId", deptId);
        createRow.setAttribute("DepartmentName", deptName);
        departmentsView1.insertRow(createRow);


    }
}

