package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 16:35:25 IST 2024
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String getDepartments(int deptId);
}

