package model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 16:43:36 IST 2024
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    String getEmployeeFullName(int employeeId);
}

