package model;

import oracle.jbo.server.ViewDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 15:53:43 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewExRowImpl extends EmployeesViewRowImpl {

    public static final int MAXUSAGECONST = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmployeeFullname;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = ViewDefImpl.getMaxAttrConst("model.EmployeesView");

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int EMPLOYEEFULLNAME = AttributesEnum.EmployeeFullname.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewExRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EmployeeFullname.
     * @return the EmployeeFullname
     */
    public String getEmployeeFullname() {
        return getFirstName()+" "+getLastName();
//        return (String) getAttributeInternal(EMPLOYEEFULLNAME);
    }
}

